Makes nested Protect Objects smarter
briis/pyunifiprotect pull request #70
Opened 2021-10-31 01:50 UTC by AngellusMortis

When trying to make everything be able to use construct, I kept running into issues with how I was handled child `ProtectBaseObject` attributes. This is a big refactor to start handling them all automatically instead of trying to manually manage them, which was a nightmare. 

This also supports attributes that have many child `ProtectBaseObject` values (lists / dicts) which there was no real support for before.

2021-10-31 01:52 UTC, AngellusMortis commented
@bdraco Feel free to review if you want/have time. Thankfully now there should not need to be a big HA testing cycle so it should save you a bunch of time.

2021-11-02 16:31 UTC, bdraco commented on pyunifiprotect/data/base.py
> +        Helper method for overriding in child classes for remapping UFP JSON keys to Python ones that do not fix the
```suggestion
        Helper method for overriding in child classes for remapping UFP JSON keys to Python ones that do not fit the
```

2021-11-02 16:32 UTC, bdraco commented on pyunifiprotect/data/base.py
>      def clean_unifi_dict(cls, data: Dict[str, Any]) -> Dict[str, Any]:
Would it make sense to name this `convert_ufp_to_native` or something similar?

2021-11-02 16:33 UTC, bdraco requested changes
Looks good.  On question on the naming.

Marking this request changes so it pings back on re-review request

2021-11-02 16:36 UTC, AngellusMortis commented on pyunifiprotect/data/base.py
>      def clean_unifi_dict(cls, data: Dict[str, Any]) -> Dict[str, Any]:
That naming could be better. The `clean_` notation came from me doing Django so much. `clean_` is just basically the common format in Django for validating/"cleaning" data. 

But since we are not in Django, `unifi_dict_to_dict` might make more sense? Since `.dict()` returns a "Python dict" and `.unifi_dict()` returns a "UFP dict"

2021-11-02 16:37 UTC, bdraco commented on pyunifiprotect/data/base.py
>      def clean_unifi_dict(cls, data: Dict[str, Any]) -> Dict[str, Any]:
> unifi_dict_to_dict

WFM 👍

2021-11-02 17:15 UTC, bdraco approved these changes

2021-11-02 17:15 UTC, merged